### PR TITLE
Initial setup + seeding script for DB

### PR DESCRIPTION
**Pull request by hongmm**
Have one giant commit for all my setup... will make sure it is more broken down next time.
In this commit, I create some folders, package,json, create a seeding script, and setup the database!

### CODE REVIEW

**Comment by jw642459986** [comment]
Looks good to me!

**Review by augustdolan — APPROVED** [review]
Hey Matt! 

Great job!
A couple of things:
1. I might define your generateScore() function before you invoke it so it is clear on first read where the function is comming from.
2. While "pineapple" isn't a sensitive password, I might take the time to move that to a git ignore file and import it. You don't want to be in a habit where you might lose your private data to a github scraper.

**Comment by hongmm** [comment]
@augustdolan I'm gonna have to ask you for more details about that but for now I am going to merge and do that in a different PR.

**Comment by augustdolan** [comment]
I'm available to chat whenever.

**Pull request merged**
